# Generated by Django 4.2.5 on 2023-09-27 19:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0004_alter_exercise_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='fitnessGoal',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('generalfitness', 'General Fitness'), ('balance', 'Balance'), ('posture', 'Posture'), ('strength', 'Strength')], max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='subcategory',
            field=models.CharField(choices=[('default_option', 'Default Option'), ('vertical_push', 'Vertical Push'), ('horizontal_push', 'Horizontal Push'), ('vertical_pull', 'Vertical Pull'), ('horizontal_pull', 'Horizontal Pull'), ('knee_flexion', 'Knee Flexion'), ('hip_dominant', 'Hip Dominant'), ('knee_dominant', 'Knee Dominant'), ('side_abs', 'Side Abs'), ('low_abs', 'Low Abs'), ('knee_felxed_abs', 'Knee Flexed Abs'), ('locomotion_abs', 'Locomotion Abs'), ('power_lowerbody', 'Power Lower Body'), ('power_upperbody', 'Power Upper Body')], max_length=255),
        ),
    ]
