# Generated by Django 4.2.5 on 2023-09-27 19:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0005_alter_exercise_fitnessgoal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='isa',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('wide_isa', 'Wide ISA'), ('narrow_isa', 'Narrow ISA'), ('unknown', 'Unknown')], default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='fitnessGoal',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('generalfitness', 'General Fitness'), ('balance', 'Balance'), ('posture', 'Posture'), ('strength', 'Strength'), ('push_up', 'First Push up'), ('pull_up', 'First Pull up'), ('single_leg_squat', 'Single Leg Squat'), ('squat', 'Squat'), ('build_back', 'Build Upper Body Muscle'), ('build_lower', 'Build Lower Body Muscle'), ('hike', 'Hike'), ('climb', 'Climb'), ('cycle', 'Cycle'), ('hill_climb_cycle', 'Hill Climb Cycling'), ('run', 'Run')], max_length=255),
        ),
    ]
