# Generated by Django 4.2.5 on 2023-10-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0012_alter_exercise_fitness_goal_alter_exercise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_warmup',
            field=models.BooleanField(default=False),
        ),
    ]
