# Generated by Django 4.2.5 on 2023-10-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0013_exercise_is_warmup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='is_warmup',
            new_name='can_be_warmup',
        ),
    ]
