# Generated by Django 4.2.1 on 2023-11-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0014_rename_is_warmup_exercise_can_be_warmup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stretch',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('kettlebell', 'Kettle Bell'), ('dumbell', 'Dumbell'), ('barbell', 'Barbell'), ('hexbar', 'Hex Bar'), ('ssb', 'SSB'), ('cable', 'Cable'), ('miniband', 'Mini Band'), ('bodyweight', 'Body Weight'), ('yogaball', 'Yoga Ball'), ('foamroller', 'Foam Roller'), ('pullup_bar', 'Pull up bar'), ('box', 'Box'), ('bar', 'Bar')], default='bodyweight', max_length=255),
        ),
    ]
