# Generated by Django 4.2.1 on 2023-11-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0016_remove_cue_cues_cue_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cue',
            name='information',
            field=models.CharField(default='Take it slow.', max_length=255),
        ),
    ]
