# Generated by Django 4.2.5 on 2023-09-27 19:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0002_exercise_fitnessgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='fitnessGoal',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('generalfitness', 'General Fitness'), ('balance', 'Balance'), ('posture', 'Posture'), ('strength', 'Strength')], default='strength', max_length=255),
        ),
    ]
