# Generated by Django 4.2.5 on 2023-09-27 19:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0006_exercise_isa_alter_exercise_fitnessgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='experience_level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='isa',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('wide_isa', 'Wide ISA'), ('narrow_isa', 'Narrow ISA'), ('both', 'Both')], default='both', max_length=255),
        ),
    ]
