# Generated by Django 4.2.5 on 2023-09-27 20:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0007_alter_exercise_experience_level_alter_exercise_isa'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='workoutLocation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('gym', 'Gym'), ('home', 'Home'), ('bodyweight', 'Body weight only workout')], default='gym', max_length=255),
        ),
    ]
