# Generated by Django 4.2.5 on 2023-09-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0008_exercise_workoutlocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='workoutLocation',
            new_name='workout_location',
        ),
    ]
