# Generated by Django 4.2.5 on 2023-09-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0010_rename_fitnessgoal_exercise_fitness_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('upper_body_posterior', 'Posterior Upper Body'), ('upper_body_anterior', 'Anterior Upper Body'), ('lower_body_posterior', 'Posterior Lower Body'), ('lower_body_anterior', 'Anterior Lower Body'), ('core', 'Core'), ('power', 'Power')], max_length=255),
        ),
    ]
