# Generated by Django 4.2.5 on 2023-10-02 16:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0011_alter_exercise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='fitness_goal',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('general_fitness', 'General Fitness'), ('balance', 'Balance'), ('posture', 'Posture'), ('strength', 'Strength'), ('push_up', 'First Push up'), ('pull_up', 'First Pull up'), ('single_leg_squat', 'Single Leg Squat'), ('squat', 'Squat'), ('build_back', 'Build Upper Body Muscle'), ('build_lower', 'Build Lower Body Muscle'), ('hike', 'Hike'), ('climb', 'Climb'), ('cycle', 'Cycle'), ('hill_climb_cycle', 'Hill Climb Cycling'), ('run', 'Run')], max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
